language: python
python:
  - "2.7"
install: "pip install PyYAML"
script: "./verify.py"
matrix:
  fast_finish: true
notifications:
  email: false
  irc:
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    channels:
        - "chat.freenode.net#rdo"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
